

public class RelationalOperations {
    public static void main(String[] args) {

        /*
            Relational operations in Java are used to compare two values.
            They return a boolean result (true or false) based on the comparison.
            The common relational operators are:
            - Equal to (==)
            - Not equal to (!=)
            - Greater than (>)
            - Less than (<)
            - Greater than or equal to (>=)
            - Less than or equal to (<=)
        */
        int a = 10;
        int b = 20;

        // Relational operations
        System.out.println("a == b: " + (a == b)); // Equal to
        System.out.println("a != b: " + (a != b)); // Not equal to
        System.out.println("a > b: " + (a > b));   // Greater than
        System.out.println("a < b: " + (a < b));   // Less than
        System.out.println("a >= b: " + (a >= b)); // Greater than or equal to
        System.out.println("a <= b: " + (a <= b)); // Less than or equal to
    }
}